### ISSUE TITLE
window.location not properly updated when using multiple routes

### ISSUE THREAD

**Issue by voondo** [atotic/excess-router#1]
Maybe is it more a question than a real issue, so sorry in advance.
As in your fully working example, if you have at least two routes like :

``` html
<excess-route
        route="/:mainmenu/(.*)"
        mainmenu="{{appRoute}}"></excess-route>
<excess-route
         route="/user/:userId"
         user-id="{{userId}}"
         active="{{hasUserId}}"></excess-route>
```

and you set

``` javascript
// this.appRoute == 'other-route'
this.appRoute = 'user'
this.userId = 23
```

the route used to build the new path (in window.location) seems to be the first whereas I want the second. How to handle that ?

**Comment by atotic** [comment]
This is what happens:

Let route="/:mainmenu/(.*)" be r1
Let route="/user/:userId" be r2

this.appRoute = 'user' causes r1 to start a transition. r2 does not transition because it is not active
this.userId does nothing because r2 is still inactive.

this might help:
make r2 route be route="/user/:userId?". This makes userId optional, so it will be active even if userId is missing. Then this.userId = 23 will cause r2 to navigate, because it is active

Other option is to just call r2.navigateTo({userId: 23})

Sorry about late reply, missed this bug report.

**Comment by voondo** [comment]
thanks a lot !
